version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - monitoring

  # grafana, monitor 서비스는 기존 설정 그대로 따름

networks:
  monitoring:
    driver: bridge